### ISSUE TITLE
BL_rst ping bug

### ISSUE THREAD

**Issue by posystorage** [yuht/TC35661-Keil#1]
[led.zip](https://github.com/yuht/TC35661-Keil/files/304529/led.zip)

蓝牙复位引脚应该是设为GPIO_InitStructure.GPIO_Mode = GPIO_Mode_Out_PP;才对
原来设的GPIO_Mode_Out_OD在stm32上没问题，但是在GD32上就用不了，引脚下拉不了。
上传改正的led.c文件

并且PA12引脚与单片机的USB引脚有冲突，移植望周知。即付宝pos（型号bz1）上用的是PC11引脚。

**Comment by yuht** [comment]
直接提交path到代码上多好呀。。

**Comment by yuht** [comment]
fix.
