### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by dongdixidi** [yuht/TC35661-Keil#3]
并没有找到所谓的usart.cpp
“3、usart.cpp文件是一个硬件串口和bt数据的接口链接文件，负责转发数据 在demo中三个串口都已经初始化为115200，默认使用串口一向外发送数据（如ttl小板），串口二向蓝牙模块发送数据。”

**Comment by yuht** [comment]
TC35661-Keil/SYSTEM/stm32_usart/stm32_usart.c

**Comment by dongdixidi** [comment]
多谢

**Comment by yuht** [comment]
错了， 在这个文件中bluetooth/common.cpp

**Comment by dongdixidi** [comment]
多谢
